#print("Hello World!")
print("Hello Again.")
print("I like typing this")
print("This is fun")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("It's good to be back in Atom learning some Python. Let's do this!")
